const token =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50IjpbeyJfaWQiOjEsInN0dWRlbnRfbmFtZSI6InRyb3kiLCJlbWFpbCI6InRyb3lAZ21haWwuY29tIiwic3RhdHVzIjoiYWN0aXZlIn1dLCJpYXQiOjE2NjE0OTMzNjl9.Fz5snzbCjYYAJVSHtkc2Eneff7_m95Ltp_4bfOhVdQY";

module.exports = token;
